name: git_clone
description: A library for cloning a git repository.
version: 1.1.0
homepage: https://github.com/g1eny0ung/git_clone
repository: https://github.com/g1eny0ung/git_clone
issue_tracker: https://github.com/g1eny0ung/git_clone/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  test: ^1.14.4
  pedantic: ^1.9.0
