name: git_clone
description: A library for cloning a git repository.
version: 1.1.0
homepage: https://github.com/g1eny0ung/git_clone
repository: https://github.com/g1eny0ung/git_clone
issue_tracker: https://github.com/g1eny0ung/git_clone/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  lints: ^3.0.0
  test: ^1.14.4
